export type DreSeedRow = {
  name: string;
  classification: string;
  transaction_type: string;
};

/** 81 contas DRE extraídas da planilha GRX V3 */
export const DRE_SEED: DreSeedRow[] = [
  { name: "Água", classification: "Ocupação", transaction_type: "Despesa" },
  { name: "Ajudante", classification: "Operacional", transaction_type: "Despesa" },
  { name: "Alimentação", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Aluguel", classification: "Ocupação", transaction_type: "Despesa" },
  { name: "Andaimes - Aquisição", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Andaimes - Locação", classification: "Receitas", transaction_type: "Receita" },
  { name: "Aquisição de bens", classification: "Operacional", transaction_type: "Despesa" },
  { name: "Assinaturas", classification: "TI", transaction_type: "Despesa" },
  { name: "Bebidas - Geladeira", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Benefícios", classification: "RH", transaction_type: "Despesa" },
  { name: "Brindes", classification: "Marketing", transaction_type: "Despesa" },
  { name: "Caminhão agregado", classification: "Operacional", transaction_type: "Despesa" },
  { name: "Cartórios/Tabelião", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Comissão", classification: "Lavagens", transaction_type: "Despesa" },
  { name: "Consórcio", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Coordenador", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Correios", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Cursos e treinamentos", classification: "RH", transaction_type: "Despesa" },
  { name: "Custo caminhão refrigerado", classification: "Operacional", transaction_type: "Despesa" },
  { name: "Custo micro Ônibus agregado", classification: "Operacional", transaction_type: "Despesa" },
  { name: "Custo ônibus agregado", classification: "Operacional", transaction_type: "Despesa" },
  { name: "Desconto de Multas - Motoristas", classification: "Receitas", transaction_type: "Receita" },
  { name: "Despesas bancárias", classification: "Finanças", transaction_type: "Despesa" },
  { name: "Despesas com transporte", classification: "Operacional", transaction_type: "Despesa" },
  { name: "Documentação Caminhão", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Documentação Vans", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Empréstimos e financiamentos", classification: "Finanças", transaction_type: "Despesa" },
  { name: "Endomarketing", classification: "Marketing", transaction_type: "Despesa" },
  { name: "Energia elétrica", classification: "Ocupação", transaction_type: "Despesa" },
  { name: "Estacionamento", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Fornecedor de marketing", classification: "Marketing", transaction_type: "Despesa" },
  { name: "Fornecedor de TI", classification: "TI", transaction_type: "Despesa" },
  { name: "Fornecimento de àgua", classification: "Ocupação", transaction_type: "Despesa" },
  { name: "Gráfica e copiadora", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Hospedagem", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Impostos", classification: "Taxas e Tributos", transaction_type: "Despesa" },
  { name: "Internet", classification: "TI", transaction_type: "Despesa" },
  { name: "KM", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Limpeza e conservação", classification: "Ocupação", transaction_type: "Despesa" },
  { name: "Manutenção de bens", classification: "Operacional", transaction_type: "Despesa" },
  { name: "Manutenção e reforma", classification: "Ocupação", transaction_type: "Despesa" },
  { name: "Materiais de lava rápido", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Materiais de TI", classification: "TI", transaction_type: "Despesa" },
  { name: "Material de escritório", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Material de limpeza e cozinha", classification: "Ocupação", transaction_type: "Despesa" },
  { name: "Motoboy", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Motorista", classification: "Operacional", transaction_type: "Despesa" },
  { name: "Móveis e utensílios", classification: "Ocupação", transaction_type: "Despesa" },
  { name: "Multas e juros", classification: "Finanças", transaction_type: "Despesa" },
  { name: "Pagamento de BV", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Pedágio", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Posto de Combustível", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Prospecção", classification: "Marketing", transaction_type: "Despesa" },
  { name: "Receita Caminhão", classification: "Receitas", transaction_type: "Receita" },
  { name: "Receita Caminhão Refrigerado", classification: "Receitas", transaction_type: "Receita" },
  { name: "Receita diversas", classification: "Receitas", transaction_type: "Receita" },
  { name: "Receita Estacionamento", classification: "Receitas", transaction_type: "Receita" },
  { name: "Receita Lava Rápido", classification: "Receitas", transaction_type: "Receita" },
  { name: "Receita micro ônibus agregado", classification: "Receitas", transaction_type: "Receita" },
  { name: "Receita ônibus agregado", classification: "Receitas", transaction_type: "Receita" },
  { name: "Receita Van", classification: "Receitas", transaction_type: "Receita" },
  { name: "Reembolso", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Salários", classification: "RH", transaction_type: "Despesa" },
  { name: "Saldo Inicial", classification: "Receitas", transaction_type: "Receita" },
  { name: "Seguros", classification: "Ocupação", transaction_type: "Despesa" },
  { name: "Serviços contábeis", classification: "Finanças", transaction_type: "Despesa" },
  { name: "Serviços de consultoria", classification: "Operacional", transaction_type: "Despesa" },
  { name: "Taxas e emolumentos", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Táxi/Uber", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Telefonia", classification: "TI", transaction_type: "Despesa" },
  { name: "Transferências bancárias", classification: "Movimentações", transaction_type: "Outros" },
  { name: "Transporte público", classification: "Administrativo", transaction_type: "Despesa" },
  { name: "Van agregada", classification: "Operacional", transaction_type: "Despesa" },
  { name: "Venda de bebidas e salgadinhos", classification: "Receitas", transaction_type: "Receita" },
  { name: "Vendas Bebidas - Geladeira", classification: "Receitas", transaction_type: "Receita" },
  { name: "Vendas Litle Tress", classification: "Receitas", transaction_type: "Receita" },
  { name: "Caminhão 1", classification: "Receitas", transaction_type: "Receita" },
  { name: "Caminhão 2", classification: "Receitas", transaction_type: "Receita" },
  { name: "Caminhão 3", classification: "Receitas", transaction_type: "Receita" },
  { name: "Van 1", classification: "Receitas", transaction_type: "Receita" },
  { name: "Van 2", classification: "Receitas", transaction_type: "Receita" },
];
